name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Set version tag
      id: tag
      run: echo "::set-output name=TAG::v${{ github.run_number }}"

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/codester:${{ steps.tag.outputs.TAG }} .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/codester:${{ steps.tag.outputs.TAG }}
